---
title: "Locating Affordable Housing"
author: "Frank Chen"
date: "2024-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(tidyverse)
library(sf)
library(units)
```

```{r load data}
land_use <- st_read("https://opendata.arcgis.com/datasets/e433504739bd41049de5d8f4a22d34ba_0.geojson")
zoning <- st_read("https://opendata.arcgis.com/datasets/0bdb0b5f13774c03abf8dc2f1aa01693_0.geojson")
property <- read.csv("https://opendata-downloads.s3.amazonaws.com/opa_properties_public.csv")
zoning_regulation <- read.csv("D:/Spatial_Optimization/Final/data/zoning.csv")
```

```{r filter}
vacant_land <- land_use %>% 
  filter(C_DIG2 == 91)

st_write(city_owned, "D:/Spatial_Optimization/Final/data/city_owned.shp")

r_area <- zoning %>% 
  filter(ZONINGGROUP == "Residential/Residential Mixed-Use")

pub_var <- c("CITY", "PHILA")

city_owned <- property %>% 
  rename(geometry = shape) %>% 
  st_as_sf(wkt = "geometry", crs = 2272) %>% 
  dplyr::select(market_value, category_code_description, owner_1, owner_2) %>% 
  filter(category_code_description == "VACANT LAND") %>% 
  mutate(owner = paste0(owner_1, " ", owner_2)) %>% 
  dplyr::select(-owner_1, -owner_2) %>% 
  filter(str_detect(owner, paste(pub_var, collapse = "|"))) %>% 
  st_transform(st_crs(vacant_land))
```

```{r spatial join}
city_owned_vland <- city_owned %>% 
  st_join(vacant_land, .) %>% 
  filter(! is.na(owner))

parcels <- city_owned_vland %>% 
  st_join(., r_area, join = st_within) %>% 
  filter(! is.na(CODE)) %>% 
  st_transform("ESRI:102728") %>% 
  mutate(area_sqft = as.numeric(set_units(st_area(geometry), "ft^2"))) %>% 
  dplyr::select(C_DIG2, owner, CODE, market_value, area_sqft, geometry)

parcels <- parcels %>% 
  left_join(., zoning_regulation, by = "CODE")

parcels_RSD <- parcels %>% 
  filter(str_detect(CODE, "RSD")) %>% 
  mutate(units = 1)

RM_var <- c("RM2", "RM3", "RM4")

parcels_RSA <- parcels %>% 
  filter(! str_detect(CODE, paste(RM_var, collapse = "|")),
         ! str_detect(CODE, "RSD"),
         area_sqft > min.lot.area) %>% 
  mutate(units = floor(area_sqft * Max.occupied / unit.area))

parcels_RM <- parcels %>% 
  filter(str_detect(CODE, paste(RM_var, collapse = "|")),
         area_sqft > min.lot.area) %>% 
  mutate(units = floor(area_sqft * FAR / unit.area))

final_parcels <- rbind(parcels_RSD, parcels_RSA, parcels_RM)

# final_parcels %>% 
#   dplyr::select(market_value, units, geometry) %>% 
#   st_write("D:/Spatial_Optimization/Final/data/parcels.shp")

# final_parcels %>% 
#   dplyr::select(market_value, units, geometry) %>% 
#   st_centroid() %>% 
#   st_write("D:/Spatial_Optimization/Final/data/parcels_nodes.shp")
```

```{r job}
low_income_jobs <- read.csv("D:/Spatial_Optimization/Final/data/pa_wac_SE01_JT03_2021.csv") %>% 
  filter(str_starts(w_geocode, "42101")) %>% 
  dplyr::select(w_geocode, CE01) %>% 
  rename(GEOID = w_geocode)

blocks <- st_read("D:/Spatial_Optimization/Final/data/tl_2023_42_tabblock20.shp") %>% 
  filter(str_starts(GEOID20, "42101")) %>% 
  dplyr::select(GEOID20, geometry) %>% 
  rename(GEOID = GEOID20) %>% 
  mutate(GEOID = as.numeric(GEOID)) %>% 
  st_transform("ESRI:102728")

jobs <- left_join(blocks, low_income_jobs, by = "GEOID")

# jobs %>% st_write("D:/Spatial_Optimization/Final/data/jobs.shp")

sum(low_income_jobs$CE01)
sum(jobs$CE01, na.rm = T)
```

```{r public transit}
bus_stops <- st_read("D:/Spatial_Optimization/Final/data/Bus_Stops_(Spring_2024).geojson") %>% 
  st_transform("ESRI:102728") %>% 
  dplyr::select(FID, geometry)

rail_stations <- st_read("D:/Spatial_Optimization/Final/data/Regional_Rail_Stations.geojson") %>% 
  st_transform("ESRI:102728") %>% 
  dplyr::select(FID, geometry)

street <- st_read("D:/Spatial_Optimization/Final/data/Street_Centerline.geojson") %>% 
  st_transform("ESRI:102728") %>% 
  dplyr::select(geometry)

# bus_stops %>% st_write("D:/Spatial_Optimization/Final/data/bus_stops.shp")
# rail_stations %>% st_write("D:/Spatial_Optimization/Final/data/rail_stations.shp")
# street %>% st_write("D:/Spatial_Optimization/Final/data/street.shp")
```

```{r}
parcels_bus <- st_read("D:/Spatial_Optimization/Final/data/parcels_bus.shp")

parcels_bus_buffer <- parcels_bus %>%
  st_buffer(dist = units::set_units(0.25, "mi")) %>% 
  group_by(FacilityID) %>% 
  summarise()

# st_write(parcels_bus_buffer, "D:/Spatial_Optimization/Final/data/parcels_bus_buffer.shp")

parcels_rail <- st_read("D:/Spatial_Optimization/Final/data/parcels_rail.shp")

parcels_rail_buffer <- parcels_rail %>%
  st_buffer(dist = units::set_units(0.5, "mi")) %>% 
  group_by(FacilityID) %>% 
  summarise()

# st_write(parcels_rail_buffer, "D:/Spatial_Optimization/Final/data/parcels_rail_buffer.shp")
```

